
CREATE TABLE USUARIO (
    Us_ID INT AUTO_INCREMENT PRIMARY KEY,
    Us_nome VARCHAR(25) NOT NULL,
    Us_email VARCHAR(150) NOT NULL UNIQUE,
    Us_senha VARCHAR(255) NOT NULL,
    Us_biografia VARCHAR(500),
    Us_SV BOOLEAN,
    Us_nivel INT NOT NULL,
    Us_XP_total INT NOT NULL DEFAULT 0,
    Us_dt_ultimo_acesso DATE NOT NULL,
    Us_adm BOOLEAN NOT NULL DEFAULT 0,
    Us_imagem VARCHAR(50)
);

CREATE TABLE OBRA (
    Ob_ID INT AUTO_INCREMENT PRIMARY KEY,
    Us_ID INT NOT NULL,
    Ob_titulo VARCHAR(100) NOT NULL,
    Ob_sinopse TEXT NOT NULL,
    Ob_genero VARCHAR(100) NOT NULL,
    Ob_status INT NOT NULL,
    Ob_imagem VARCHAR(250),

    CONSTRAINT FK_OBRA_USUARIO
        FOREIGN KEY (Us_ID)
        REFERENCES USUARIO(Us_ID)
);


CREATE TABLE CAPITULO (
    Cap_ID INT AUTO_INCREMENT PRIMARY KEY,
    Ob_ID INT NOT NULL,
    Cap_ordem INT NOT NULL,
    Cap_titulo VARCHAR(100) NOT NULL,
    Cap_conteudo TEXT,

    CONSTRAINT FK_CAPITULO_OBRA
        FOREIGN KEY (Ob_ID)
        REFERENCES OBRA(Ob_ID)
);


CREATE TABLE CHAT_USUARIO (
    Chat_ID INT AUTO_INCREMENT PRIMARY KEY,
    Chat_remetente INT NOT NULL,
    Chat_destinatario INT NOT NULL,
    Chat_data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Chat_mensagem TEXT NOT NULL,
    Chat_status BOOLEAN NOT NULL DEFAULT 0,

    CONSTRAINT FK_CHAT_REMETENTE
        FOREIGN KEY (Chat_remetente)
        REFERENCES USUARIO(Us_ID),

    CONSTRAINT FK_CHAT_DESTINATARIO
        FOREIGN KEY (Chat_destinatario)
        REFERENCES USUARIO(Us_ID)
);


CREATE TABLE MISSOES (
    Ms_ID INT AUTO_INCREMENT PRIMARY KEY,
    Ms_titulo VARCHAR(100) NOT NULL,
    Ms_descricoo VARCHAR(500) NOT NULL,
    Ms_recompensaXP INT NOT NULL,
    Ms_Tipo VARCHAR(50) NOT NULL
);


CREATE TABLE USUARIO_MISSAO (
    Us_ID INT NOT NULL,
    Ms_ID INT NOT NULL,
    Um_Status VARCHAR(50) NOT NULL,
    Um_Dtconclução DATE,

    PRIMARY KEY (Us_ID, Ms_ID),

    CONSTRAINT FK_USUARIO_MISSAO_USUARIO
        FOREIGN KEY (Us_ID)
        REFERENCES USUARIO(Us_ID),

    CONSTRAINT FK_USUARIO_MISSAO_MISSAO
        FOREIGN KEY (Ms_ID)
        REFERENCES MISSOES(Ms_ID)
);


CREATE TABLE FAVORITOS_SALVOS (
    Ob_ID INT NOT NULL,
    Us_ID INT NOT NULL,
    Fav_status VARCHAR(50) NOT NULL,
    Ob_PagAtual INT NOT NULL,

    PRIMARY KEY (Ob_ID, Us_ID),

    CONSTRAINT FK_FAVORITOS_OBRA
        FOREIGN KEY (Ob_ID)
        REFERENCES OBRA(Ob_ID),

    CONSTRAINT FK_FAVORITOS_USUARIO
        FOREIGN KEY (Us_ID)
        REFERENCES USUARIO(Us_ID)
);


CREATE TABLE SEGUINDO (
    Us_ID INT NOT NULL,
    Seguindo INT NOT NULL,

    PRIMARY KEY (Us_ID, Seguindo),

    CONSTRAINT FK_SEGUINDO_USUARIO
        FOREIGN KEY (Us_ID)
        REFERENCES USUARIO(Us_ID),

    CONSTRAINT FK_SEGUINDO_ALVO
        FOREIGN KEY (Seguindo)
        REFERENCES USUARIO(Us_ID)
);


CREATE TABLE COMENTARIO_OBRA (
    Com_ID INT AUTO_INCREMENT PRIMARY KEY,
    Us_ID INT NOT NULL,
    Ob_ID INT NOT NULL,
    Com_obr_Dtenvio DATETIME NOT NULL,
    Com_obr_texto TEXT NOT NULL,
    Com_obr_moderacao VARCHAR(100) NOT NULL,

    CONSTRAINT FK_COMENTARIO_USUARIO
        FOREIGN KEY (Us_ID)
        REFERENCES USUARIO(Us_ID),

    CONSTRAINT FK_COMENTARIO_OBRA
        FOREIGN KEY (Ob_ID)
        REFERENCES OBRA(Ob_ID)
);
